### ISSUE TITLE
45443-3503-27.xml parse error 

### ISSUE THREAD

**Issue by koswatana** [JDA-DM/mojxml2geojson#20]
https://www.geospatial.jp/ckan/dataset/houmusyouchizu-2022-1-1973

```
% docker run --rm -v $(pwd)/data:/data mojxml2geojson /data/45443-3503-27.xml

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mojxml2geojson/core.py", line 24, in main
    package.xml2geojson.SaveGeoJson(srcFile, exclude_flag)
  File "/usr/local/lib/python3.10/site-packages/package/xml2geojson.py", line 12, in SaveGeoJson
    moj_obj = MojXml(src_file)
  File "/usr/local/lib/python3.10/site-packages/package/xml2geojson.py", line 27, in MojXml
    moj_dict = xmltodict.parse(xml_data)
  File "/usr/local/lib/python3.10/site-packages/xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 654697, column 10
Error Source File: /data/45443-3503-27.xml
```

https://github.com/JDA-DM/mojxml2geojson/issues/12
こちらと同じくXMLに制御が含まれているケース

**Comment by koswatana** [comment]
以下の行に制御文字が含まれる
```
% cat -n 45443-3503-27.xml| grep "^\"                  

654697				<名称>-!}.D-(I8</名称>
654703				<名称>-!}.E-(I8</名称>
654709				<名称>-!}.V-8r</名称>
654715				<名称>-!}.W-8r</名称>
654721				<名称>-&amp;.D-(I</名称>
654727				<名称>-&amp;.E-(I</名称>
654733				<名称>-&amp;.W3</名称>
654739				<名称>-&amp;.W4</名称>
654745				<名称>-&amp;.W5</名称>
654751				<名称>-&amp;.W6</名称>
654763				<名称>-&amp;8r.D-(</名称>
654769				<名称>-&amp;8r.V7</名称>
654775				<名称>-&amp;8r.W2</名称>
654781				<名称>-(m2&lt;D9Ln.</名称>
654787				<名称>-(n1JLn.</名称>
654793				<名称>-(nC+Fb.</名称>
```

**Comment by koswatana** [comment]
2023/08/31 法務省　登記所備付地図データ2023年版の公開について
https://front.geospatial.jp/news/2023/08/3290/

2023/10/18 法務省の登記所備付地図データ2023年版をシェープファイル、GeoJSONファイルに変換したデータを公開しました
https://front.geospatial.jp/news/2023/10/3622/

**Comment by koswatana** [comment]
45443-3503-27.xml
2023年版のデータ
https://www.geospatial.jp/ckan/dataset/houmusyouchizu-2023-1-1976
![image](https://github.com/digital-go-jp/mojxml2geojson/assets/103909883/a0aa6b03-177f-4494-b995-71bf80d5854b)

**Comment by koswatana** [comment]
2023年版のデータでは直っていそう
```
% cat -n ./2022data/45443-3503-27.xml| grep "^\"   
654697				<名称>-!}.D-(I8</名称>
654703				<名称>-!}.E-(I8</名称>
654709				<名称>-!}.V-8r</名称>
654715				<名称>-!}.W-8r</名称>
654721				<名称>-&amp;.D-(I</名称>
654727				<名称>-&amp;.E-(I</名称>
654733				<名称>-&amp;.W3</名称>
654739				<名称>-&amp;.W4</名称>
654745				<名称>-&amp;.W5</名称>
654751				<名称>-&amp;.W6</名称>
654763				<名称>-&amp;8r.D-(</名称>
654769				<名称>-&amp;8r.V7</名称>
654775				<名称>-&amp;8r.W2</名称>
654781				<名称>-(m2&lt;D9Ln.</名称>
654787				<名称>-(n1JLn.</名称>
654793				<名称>-(nC+Fb.</名称>
% cat -n ./2022data/45443-3503-27.xml| grep -c "^\"
16
% cat -n ./2023data/45443-3503-27.xml| grep "^\"
% cat -n ./2023data/45443-3503-27.xml| grep -c "^\"
0
```

変換はできた
```
% docker run --rm -v $(pwd)/2023data:/data mojxml2geojson /data/45443-3503-27.xml
% ls -al ./2023data 
total 39368
drwxr-xr-x   4 zero3  staff       128 10 27 16:53 .
drwxr-xr-x  16 zero3  staff       512 10 27 16:56 ..
-rw-r--r--   1 zero3  staff   1057706 10 27 17:04 45443-3503-27.geojson
-rw-r--r--@  1 zero3  staff  19038425  2 14  2023 45443-3503-27.xml
% docker run --rm -v $(pwd)/2023data:/data mojxml2geojson /data/45443-3503-27.xml
% cat ./2023data/45443-3503-27.geojson|jq|head
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
% cat ./2023data/45443-3503-27.geojson|jq|tail
      }
    }
  ],
  "crs": {
    "properties": {
      "name": "urn:ogc:def:crs:EPSG::6668"
    },
    "type": "name"
  }
}
```

**Comment by zero3kw** [comment]
2023年版のデータでは直っていそう
```
% cat -n ./2022data/45443-3503-27.xml| grep "^\"   
654697				<名称>-!}.D-(I8</名称>
654703				<名称>-!}.E-(I8</名称>
654709				<名称>-!}.V-8r</名称>
654715				<名称>-!}.W-8r</名称>
654721				<名称>-&amp;.D-(I</名称>
654727				<名称>-&amp;.E-(I</名称>
654733				<名称>-&amp;.W3</名称>
654739				<名称>-&amp;.W4</名称>
654745				<名称>-&amp;.W5</名称>
654751				<名称>-&amp;.W6</名称>
654763				<名称>-&amp;8r.D-(</名称>
654769				<名称>-&amp;8r.V7</名称>
654775				<名称>-&amp;8r.W2</名称>
654781				<名称>-(m2&lt;D9Ln.</名称>
654787				<名称>-(n1JLn.</名称>
654793				<名称>-(nC+Fb.</名称>
% cat -n ./2022data/45443-3503-27.xml| grep -c "^\"
16
% cat -n ./2023data/45443-3503-27.xml| grep "^\"
% cat -n ./2023data/45443-3503-27.xml| grep -c "^\"
0
```

変換はできた
```
% docker run --rm -v $(pwd)/2023data:/data mojxml2geojson /data/45443-3503-27.xml
% ls -al ./2023data 
total 39368
drwxr-xr-x   4 zero3  staff       128 10 27 16:53 .
drwxr-xr-x  16 zero3  staff       512 10 27 16:56 ..
-rw-r--r--   1 zero3  staff   1057706 10 27 17:04 45443-3503-27.geojson
-rw-r--r--@  1 zero3  staff  19038425  2 14  2023 45443-3503-27.xml
% docker run --rm -v $(pwd)/2023data:/data mojxml2geojson /data/45443-3503-27.xml
% cat ./2023data/45443-3503-27.geojson|jq|head
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
% cat ./2023data/45443-3503-27.geojson|jq|tail
      }
    }
  ],
  "crs": {
    "properties": {
      "name": "urn:ogc:def:crs:EPSG::6668"
    },
    "type": "name"
  }
}
```

**Comment by koswatana** [comment]
2023年版のデータでは直っていそう
```
% cat -n ./2022data/45443-3503-27.xml| grep "^\"   
654697				<名称>-!}.D-(I8</名称>
654703				<名称>-!}.E-(I8</名称>
654709				<名称>-!}.V-8r</名称>
654715				<名称>-!}.W-8r</名称>
654721				<名称>-&amp;.D-(I</名称>
654727				<名称>-&amp;.E-(I</名称>
654733				<名称>-&amp;.W3</名称>
654739				<名称>-&amp;.W4</名称>
654745				<名称>-&amp;.W5</名称>
654751				<名称>-&amp;.W6</名称>
654763				<名称>-&amp;8r.D-(</名称>
654769				<名称>-&amp;8r.V7</名称>
654775				<名称>-&amp;8r.W2</名称>
654781				<名称>-(m2&lt;D9Ln.</名称>
654787				<名称>-(n1JLn.</名称>
654793				<名称>-(nC+Fb.</名称>
% cat -n ./2022data/45443-3503-27.xml| grep -c "^\"
16
% cat -n ./2023data/45443-3503-27.xml| grep "^\"
% cat -n ./2023data/45443-3503-27.xml| grep -c "^\"
0
```

変換はできた
```
% docker run --rm -v $(pwd)/2023data:/data mojxml2geojson /data/45443-3503-27.xml
% ls -al ./2023data 
total 39368
drwxr-xr-x   4 zero3  staff       128 10 27 16:53 .
drwxr-xr-x  16 zero3  staff       512 10 27 16:56 ..
-rw-r--r--   1 zero3  staff   1057706 10 27 17:04 45443-3503-27.geojson
-rw-r--r--@  1 zero3  staff  19038425  2 14  2023 45443-3503-27.xml
% docker run --rm -v $(pwd)/2023data:/data mojxml2geojson /data/45443-3503-27.xml
% cat ./2023data/45443-3503-27.geojson|jq|head
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
% cat ./2023data/45443-3503-27.geojson|jq|tail
      }
    }
  ],
  "crs": {
    "properties": {
      "name": "urn:ogc:def:crs:EPSG::6668"
    },
    "type": "name"
  }
}
```
